# Spring boot overrides

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:26257/orders?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      connection-timeout: 5000
      validation-timeout: 20000
      max-lifetime: 180000
      idle-timeout: 60000
      maximum-pool-size: 15
      minimum-idle: 0
      transaction-isolation: TRANSACTION_SERIALIZABLE
      auto-commit: true
      data-source-properties:
        reWriteBatchedInserts: true

---
spring:
  config:
    activate:
      on-profile: secure
  datasource:
    url: jdbc:postgresql://localhost:26257/orders?sslmode=require
    username: craig
    password: cockroach
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE

---
spring:
  config:
    activate:
      on-profile: cloud
  datasource:
    url: jdbc:postgresql://valhalla-qzx.aws-eu-north-1.cockroachlabs.cloud:26257/orders?sslmode=require
    username: craig
    password: cockroach
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://192.168.1.99:26257/orders?sslmode=disable
